version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_PASSWORD=${APP_PASSWORD}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - PORT=8080
    restart: unless-stopped
