services:
  app:
    build: .
    image: cloudflare-dns-manager:latest
    ports:
      - "8080:8080"
    environment:
      - APP_PASSWORD=${APP_PASSWORD}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - PORT=8080
    # Uncomment to see container logs easily
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
